# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551731d29f74556ad6f54d94f301cff25e7a81a336b3ec122eabcb03d4558aefa3de5635e8f900e9e5e78d98d7eb011239e9ac15f6306592aad4eb1018ed6508

test:
  secret_key_base: 4e0e47bfa2f1a557cfda9b9051883687f8da1136a3a977ce226cd284d5e637d3dbd5f16b3e915816b8d93ceda59dfc6e30fe5c1a2474a414d7bca4bb2872af6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
